### ISSUE TITLE
.project-tile.png exists - no image in viewer

### ISSUE THREAD

**Issue by bennyp123** [EXSyst/recent-projects#37]
Howdy, when I open a new window, I see blank grey in the project icon field, no default icon or project logos, although .project-tile.png files exist.

**Comment by Ener-Getick** [comment]
Can you check if the icon is present in the html with the dev tools please?

**Comment by bennyp123** [comment]
The files I added to the project folders don't appear to be loaded.
![screen shot 2015-11-01 at 12 08 24 pm](https://cloud.githubusercontent.com/assets/1466420/10868279/ea8bf9aa-8091-11e5-8f80-2626bbdfd10c.png)

**Comment by Ener-Getick** [comment]
I'll try to reorganize the code.
Is your ``.project-tile.png`` in your remote (``ftp://...``) or in your local folder ?

Can you paste the html code corresponding to your ``Recent projects`` tab please ?

**Comment by bennyp123** [comment]
local folder. here's the HTML (redacted)

```
<body tabindex="-1" class="platform-darwin is-blurred">


<atom-workspace class="workspace scrollbars-visible-when-scrolling theme-one-dark-syntax theme-one-dark-ui" tabindex="-1"><atom-workspace-axis class="horizontal"><atom-panel-container class="left"></atom-panel-container><atom-workspace-axis class="vertical"><atom-panel-container class="top"></atom-panel-container><atom-pane-container class="panes"><atom-pane class="pane active" tabindex="-1" style="flex-grow: 1;"><ul tabindex="-1" class="list-inline tab-bar inset-panel" is="space-pen-ul"><li is="tabs-tab" class="tab sortable active" data-type="RecentProjectsView"><div class="title icon icon-repo">Recent Projects</div><div class="close-icon"></div></li><li is="tabs-tab" class="tab sortable modified" data-type="TextEditor"><div class="title">untitled</div><div class="close-icon"></div></li></ul><div class="item-views"><div class="recent-projects-view pane-item padded" tabindex="0" is="space-pen-div"><div class="actions-bar"><button class="btn btn-default icon icon-file-directory" click="openFolder">Open Folder...</button><button class="btn btn-default icon icon-file-code" click="createNewFile">New File</button></div><div class="alert alert-danger hidden"></div><ul class="project-list show-git-branch show-last-opened show-extra-paths show-ftp-url"><li class="project-entry btn btn-default stared" is="space-pen-li"><div class="project-meta"><div class="project-title">BennyPowers.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:22:45 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://@bennypowers.com@ftp.bennypowers.com/</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default icon icon-repo" is="space-pen-li"><div class="project-meta"><div class="project-title">config</div><div class="project-url icon icon-file-directory">/atom:</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Mon, 02 Nov 2015 06:57:34 GMT">11 hours ago</time></div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default icon icon-repo" is="space-pen-li"><div class="project-meta"><div class="project-title">disk-usage.widget</div><div class="project-url icon icon-file-directory">~/Library/Application Support/Übersicht/widgets</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 21:51:06 GMT">20 hours ago</time></div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li"><div class="project-meta"><div class="project-title">.org</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects/Ideas</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 10:05:41 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://@.com@f..com/public_html</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li" style="background-image: url(file:///Users/bennyp/.atom/packages/recent-projects/.project-tile.png);"><div class="project-meta"><div class="project-title">recent-projects</div><div class="project-url icon icon-file-directory">~/.atom/packages</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:25:23 GMT">yesterday</time></div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default icon icon-repo" is="space-pen-li"><div class="project-meta"><div class="project-title">.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:22:41 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://.com@.com/</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li"><div class="project-meta"><div class="project-title">.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:20:55 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://.com@.com/</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li"><div class="project-meta"><div class="project-title">.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:20:48 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://.com@.com/</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li"><div class="project-meta"><div class="project-title">.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:11:55 GMT">yesterday</time></div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li><li class="project-entry btn btn-default" is="space-pen-li"><div class="project-meta"><div class="project-title">.com</div><div class="project-url icon icon-file-directory">~/Documents/Web Projects/Ideas</div><br><div class="project-meta-mini project-date icon icon-clock"><time datetime="Sun, 01 Nov 2015 06:06:22 GMT">yesterday</time></div><div class="project-meta-mini project-ftp-url icon icon-link">ftp://.com@.com/public_html</div></div><button class="project-star btn btn-danger icon icon-star"></button><button class="project-delete btn btn-danger icon icon-x"></button></li></ul></div><atom-text-editor class="editor" tabindex="-1" data-grammar="text plain null-grammar" data-encoding="utf8" style="display: none;"></atom-text-editor></div></atom-pane></atom-pane-container><atom-panel-container class="bottom"><atom-panel class="bottom tool-panel panel-bottom"><status-bar class="status-bar"><div class="flexbox-repaint-hack"><div class="status-bar-left"><div is="status-bar-file" class="file-info inline-block" data-original-title="" title=""><a class="current-path">Recent Projects</a></div><div is="status-bar-cursor" class="cursor-position inline-block hide" data-original-title="" title=""><a class="inline-block" href="#"></a></div><div is="status-bar-selection" class="selection-count inline-block" data-original-title="" title=""></div><div class="status-image inline-block" is="space-pen-div"><span class="image-size" style="display: none;"></span></div></div><div class="status-bar-right"><a class="line-ending-tile inline-block"></a><encoding-selector-status class="encoding-status inline-block" style="display: none;"><a class="inline-block" href="#" data-encoding="utf8">UTF-8</a></encoding-selector-status><grammar-selector-status class="grammar-status inline-block" style="display: none;"><a class="inline-block" href="#" data-grammar="Plain Text">Plain Text</a></grammar-selector-status><div is="status-bar-git" class="git-view"><div class="git-branch inline-block" style="display: none;"><span class="icon icon-git-branch"></span><span class="branch-label"></span></div><div class="git-commits inline-block" style="display: none;"><span class="icon icon-arrow-up commits-ahead-label"></span><span class="icon icon-arrow-down commits-behind-label"></span></div><div class="git-status inline-block" style="display: none;"><span class="icon"></span></div></div></div></div></status-bar></atom-panel></atom-panel-container></atom-workspace-axis><atom-panel-container class="right"></atom-panel-container></atom-workspace-axis><atom-panel-container class="modal"><atom-panel class="modal overlay from-top" style="display: none;"><div class="select-list" is="space-pen-div"><atom-text-editor class="editor mini" tabindex="-1" mini="" data-grammar="text plain null-grammar" data-encoding="utf8"></atom-text-editor><div class="error-message" style="display: none;"></div><div class="loading" style="display: none;"><span class="loading-message"></span><span class="badge"></span></div><ol class="list-group"><li class="selected">LF</li><li>CRLF</li></ol></div></atom-panel></atom-panel-container></atom-workspace></body>
```

**Comment by Ener-Getick** [comment]
Hum that's strange, I'll try to fix this during the week if I can localize the issue. 
Thank you for your help :-)

**Comment by Ener-Getick** [comment]
Does the latest version fix this issue ?

**Comment by bennyp123** [comment]
I get this: (would have pasted but atom doesn't let me copy the stack trace)

![screen shot 2015-11-03 at 10 47 11 pm](https://cloud.githubusercontent.com/assets/1466420/10921216/dfc0d4f4-827c-11e5-9df2-deabef73dbcc.png)

**Comment by Ener-Getick** [comment]
I fixed this in the v0.9.3.

**Comment by bennyp123** [comment]
I've updated to 0.9.3 and still don't see .project-tile.png in the recent projects window. 

The issue is caused by a space in the parent directory name (~/Documents/Web Projects). When i rename that dir to WebProjects, remove and re-add project folders from Atom, the tiles appear as expected.

**Comment by Ener-Getick** [comment]
The image path is now escaped.

Before: ``background-image: url(file://Web Projects);``
Now: ``background-image: url(file://Web%20Projects);``

**Comment by bennyp123** [comment]
👍🏻
